apiVersion: v1
kind: ServiceAccount
metadata:
  name: mango-issuer
  namespace: mango

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mango-issuer
  namespace: mango
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['mango-issuer']
    verbs: ['create']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mango-issuer
  namespace: mango
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mango-issuer


