apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-issuer
  namespace: nginx

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-issuer
  namespace: nginx
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['nginx-issuer']
    verbs: ['create']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-issuer
  namespace: nginx
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-issuer


